name: RHS Bare Metal Core CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test_with_quick_project:
    runs-on: [self-hosted]
    name: Build RPLC_M
    
    steps:
      - name: Checkout Quick Project
        uses: actions/checkout@v4
        with:
          repository: RoboticsHardwareSolutions/RPLC_Quick_Project
          path: quick_project
          submodules: 'recursive'

      - name: Replace core submodule with current version
        run: |
          cd quick_project/thirdparty/rhs

          TARGET_BRANCH=${{ github.event.pull_request.head.ref || github.ref_name }}
          git config remote.origin.fetch "+refs/heads/$TARGET_BRANCH:refs/remotes/origin/$TARGET_BRANCH"
          git fetch origin --depth=1
          git checkout -f $TARGET_BRANCH

      - name: Configure project
        run: |
          cd quick_project
          mkdir build
          cd build
          cmake -DPLC_TYPE="RPLC_M" ..
          
      - name: Build project
        run: |
          cd quick_project/build
          cmake --build .
          
      - name: Flash firmware
        run: |
            cd quick_project
            python3 .github/scripts/flashing.py ${{ secrets.JLINK_SERIAL_CI_BMPLC_M }} STM32F103RE build/rplc.bin 

      - name: Unit tests
        run: |
            cd quick_project
            python3 .github/scripts/units.py ${{ secrets.JLINK_SERIAL_CI_BMPLC_M }} STM32F103RE
